ktor:
  deployment:
    port: 8080

  application:
    modules:
      - com.stocklogistic.HttpKt.configureHttp
      - com.stocklogistic.SerializationKt.configureSerialization
      - com.stocklogistic.RoutingKt.configureRouting
